site_name: MMI ORR
repo_url: https://github.com/mmisw/mmiorr-docs
theme: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: True

pages:
- Home: index.md
- About: about.md
- Introduction: introduction.md
- Getting Started: gettingstarted.md
- FAQ: faq.md
- Searching and Querying:
  - Searching via the UI: search.md
  - Querying via REST API: api/query.md
  - Querying via SPARQL API: query.md
- Working with Vocabularies:
  - Creating a Vocabulary: vocab/new.md
  - Importing a Vocabulary: vocab/import.md
  - Viewing a Vocabulary: vocab/view.md
  - Updating a Vocabulary: vocab/newversion.md
  - Registering a Vocabulary: vocab/register.md
- Working with Ontologies:
  - Registering Your Existing Ontology: ontology/new.md
  - Updating an Ontology: ontology/newversion.md
- Working with Mappings:
  - Creating a Mapping Ontology: mapping/new.md
  - Updating a Mapping Ontology: mapping/newversion.md
- REST API: api/index.md
- Advanced Topics:
  - Known issues: knownissues.md
  - Installation: install/index.md
