site_name: MMI ORR
repo_url: https://github.com/mmisw/mmiorr-docs
theme: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: True

pages:
- Home: index.md
- About: about.md
- Introduction: introduction.md
- Installation: install/index.md
- Getting Started: gettingstarted.md
- FAQ: faq.md
- Working with Vocabularies:
  - Creating a Vocabulary: vocab/new.md
  - Viewing a Vocabulary: vocab/view.md
  - Creating a New Version of a Vocabulary: vocab/newversion.md
- Working with Mappings:
  - Creating a Mapping Ontology: mapping/new.md
  - Creating a New Version of a Mapping Ontology: mapping/newversion.md
- Registering Your Existing Ontology: upload.md
- Querying Content via API: query.md
- REST API: api/index.md
- Known issues: knownissues.md
