site_name: MMI ORR
repo_url: https://github.com/mmisw/mmiorr-docs
theme: readthedocs

markdown_extensions:
  - admonition
  - toc:
      permalink: True

pages:
- Home: index.md
- About: about.md
- Introduction: introduction.md
- Installation: install/index.md
- Getting Started: gettingstarted.md
- FAQ: faq.md
- Searching and Querying:
  - Searching via the UI: search.md
  - Querying via REST API: api/index.md
  - Querying via SPARQL API: query.md
- Working with Vocabularies:
  - Creating a Vocabulary: vocab/new.md
  - Importing a Vocabulary: vocab/import.md
  - Viewing a Vocabulary: vocab/view.md
  - Creating a New Version of a Vocabulary: vocab/newversion.md
- Working with Ontologies:
  -  Registering Your Existing Ontology: upload.md
- Working with Mappings:
  - Creating a Mapping Ontology: mapping/new.md
  - Creating a New Version of a Mapping Ontology: mapping/newversion.md
- Known issues: knownissues.md
